services:
  backend:
    extends:
      file: ./nest/docker-compose.yml
      service: backend
    networks:
      - backend_network
      - frontend_network
    volumes:
      - ./nest:/app # Map nest directory to /app in container
      - /app/node_modules # Prevent overwriting node_modules
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  postgres:
    extends:
      file: ./nest/docker-compose.yml
      service: postgres
    networks:
      - backend_network

  redis:
    extends:
      file: ./nest/docker-compose.yml
      service: redis
    networks:
      - backend_network

  prisma-studio:
    extends:
      file: ./nest/docker-compose.yml
      service: prisma-studio

  prisma-seed:
    extends:
      file: ./nest/docker-compose.yml
      service: prisma-seed

  frontend:
    extends:
      file: ./UI/docker-compose.yml
      service: frontend
    # ADD THESE VOLUMES for frontend too
    volumes:
      - ./UI:/app # Map UI directory to /app in container
      - /app/node_modules # Prevent overwriting node_modules

volumes:
  postgres_data:
  redis_data:

networks:
  frontend_network:
    driver: bridge
  backend_network:
    driver: bridge
