services:
  backend:
    extends:
      file: ./nest/docker-compose.yml
      service: backend

  postgres:
    extends:
      file: ./nest/docker-compose.yml
      service: postgres

  redis:
    extends:
      file: ./nest/docker-compose.yml
      service: redis

  prisma-studio:
    extends:
      file: ./nest/docker-compose.yml
      service: prisma-studio

  frontend:
    extends:
      file: ./UI/docker-compose.yml
      service: frontend

volumes:
  postgres_data:

networks:
  frontend_network:
  backend_network:
